[workspace]
members = [
]
[package]
name = "rusty_head"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2021"
autobins = false

[lib]
name = "rusty_head"
path = "lib.rs"
crate-type = ["staticlib", "rlib"]
[[bin]]
path = "src/head.rs"
name = "head"
[dependencies]
libc= "0.2"
